In [1]:
import numpy as np

In [2]:
# Example usage:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 1])  # OR Gate

In [3]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [4]:
X.shape

(4, 2)

In [5]:
y

array([0, 1, 1, 1])

In [6]:
y.shape

(4,)

In [7]:
# Add bias term to input features
X_bias = np.hstack((np.ones((X.shape[0], 1)), X))

#X = np.hstack([np.ones_like(sqft_normalized), sqft_normalized])


In [8]:
X_bias


array([[1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [9]:
X_bias.shape

(4, 3)

In [10]:
# Initialize parameters
weights = np.zeros(X_bias.shape[1])

In [11]:
weights

array([0., 0., 0.])

In [12]:
learning_rate=0.01
num_iterations=10000

In [13]:
def sigmoid(z):
        return 1 / (1 + np.exp(-z))

In [14]:
X_bias.T

array([[1., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 1., 0., 1.]])

In [15]:
y

array([0, 1, 1, 1])

In [16]:
np.dot(X_bias.T,y)

array([3., 2., 2.])

In [17]:
# Perform gradient descent
for _ in range(num_iterations):
    # Compute predictions
    linear_output = np.dot(X_bias, weights)
    y_pred = sigmoid(linear_output)

    # Compute gradient of binary cross-entropy loss w.r.t. parameters
    gradient = np.dot(X_bias.T, (y_pred - y)) / len(y)
    print(gradient)

    # Update parameters using gradient descent
    weights = weights - learning_rate * gradient

[-0.25 -0.25 -0.25]
[-0.24875    -0.24921875 -0.24921875]
[-0.24750511 -0.24844055 -0.24844055]
[-0.24626531 -0.2476654  -0.2476654 ]
[-0.24503061 -0.24689329 -0.24689329]
[-0.24380101 -0.24612425 -0.24612425]
[-0.24257652 -0.24535827 -0.24535827]
[-0.24135711 -0.24459534 -0.24459534]
[-0.24014281 -0.24383549 -0.24383549]
[-0.23893359 -0.2430787  -0.2430787 ]
[-0.23772947 -0.24232498 -0.24232498]
[-0.23653043 -0.24157434 -0.24157434]
[-0.23533647 -0.24082676 -0.24082676]
[-0.23414759 -0.24008226 -0.24008226]
[-0.23296379 -0.23934083 -0.23934083]
[-0.23178506 -0.23860248 -0.23860248]
[-0.23061139 -0.2378672  -0.2378672 ]
[-0.22944277 -0.23713499 -0.23713499]
[-0.22827921 -0.23640586 -0.23640586]
[-0.2271207 -0.2356798 -0.2356798]
[-0.22596722 -0.23495681 -0.23495681]
[-0.22481877 -0.23423688 -0.23423688]
[-0.22367535 -0.23352003 -0.23352003]
[-0.22253694 -0.23280624 -0.23280624]
[-0.22140353 -0.23209551 -0.23209551]
[-0.22027513 -0.23138784 -0.23138784]
[-0.21915171 -0.23068322 -0.23068

In [18]:
weights

array([-1.46559459,  4.01008954,  4.01008954])

In [19]:
X_test = np.array([[1, 1], [0, 0], [1, 0], [1, 1]])
X_test_bias = np.hstack((np.ones((X_test.shape[0], 1)), X_test))

In [20]:
X_test

array([[1, 1],
       [0, 0],
       [1, 0],
       [1, 1]])

In [21]:
X_test_bias

array([[1., 1., 1.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [22]:
test_linear_output = np.dot(X_test_bias, weights)

In [23]:
test_linear_output

array([ 6.55458449, -1.46559459,  2.54449495,  6.55458449])

In [24]:
probabilities = sigmoid(test_linear_output)

In [25]:
probabilities

array([0.99857845, 0.18761314, 0.92720281, 0.99857845])

In [26]:
threshold=0.5

In [27]:
predictions = np.where(probabilities >= threshold, 1, 0)

In [28]:
predictions

array([1, 0, 1, 1])